# Generated by Django 5.0.6 on 2024-05-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=3000)),
                ('created_up', models.DateTimeField()),
            ],
        ),
    ]
