# Generated by Django 5.0.6 on 2024-05-31 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CarAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('price', models.FloatField(null=True)),
                ('color', models.CharField(max_length=16)),
                ('year', models.IntegerField(null=True)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('fuel_type', models.CharField(max_length=32)),
                ('engine', models.FloatField(null=True)),
                ('mileage', models.FloatField(null=True)),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='media/%Y/%m/%d')),
                ('description', models.TextField(max_length=3000)),
                ('rear_view', models.BooleanField(default=False)),
                ('hatch', models.BooleanField(default=False)),
                ('parking_radar', models.BooleanField(default=False)),
                ('abs', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('your_name', models.CharField(max_length=32)),
                ('phone_number', models.IntegerField(null=True)),
                ('your_email', models.EmailField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.category')),
            ],
        ),
    ]
