# Generated by Django 5.0.6 on 2024-05-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='abs',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='hatch',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='parking_radar',
        ),
        migrations.RemoveField(
            model_name='caradvertisement',
            name='rear_view',
        ),
        migrations.AddField(
            model_name='caradvertisement',
            name='equipment',
            field=models.ManyToManyField(to='advertisement.equipment'),
        ),
    ]
