# Generated by Django 5.0.6 on 2024-05-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='created_up',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.CharField(default='Default City', max_length=32),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='model',
            field=models.CharField(default='Default Model', max_length=32),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
