# Generated by Django 5.0.6 on 2024-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvertisement',
            name='vip_car',
            field=models.BooleanField(default=False),
        ),
    ]
