# Generated by Django 5.0.6 on 2024-07-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_caradvertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvertisement',
            name='car_status',
            field=models.CharField(blank=True, choices=[('APPROVE', 'approve'), ('PENDING', 'pending'), ('REJECTED', 'rejected')], default='PENDING', max_length=32, null=True),
        ),
    ]
