# Generated by Django 5.0.6 on 2024-07-09 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_caradvertisement_vip_car'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvertisement',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
