# Generated by Django 5.0.6 on 2024-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='model',
            field=models.CharField(max_length=32),
        ),
    ]
