# Generated by Django 5.0.6 on 2024-07-10 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_caradvertisement_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvertisement',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
