# Generated by Django 5.0.6 on 2024-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_fueltype_alter_caradvertisement_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='caradvertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
