# Generated by Django 5.0.6 on 2024-06-05 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_caradvertisement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caradvertisement',
            name='image',
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='media/%Y/%m/%d')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.caradvertisement')),
            ],
        ),
    ]
