# Generated by Django 5.0.6 on 2024-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_caradvertisement_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='media/%Y/%m/%d'),
        ),
    ]
