# Generated by Django 5.0.6 on 2024-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_city_alter_advertisement_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='fuel_type',
            field=models.CharField(default='defaulttype', max_length=32),
        ),
    ]
