# Generated by Django 5.0.6 on 2024-06-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_remove_caradvertisement_image_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.FileField(blank=True, default='fallback.png', upload_to='media/%Y/%m/%d'),
        ),
    ]
