# Generated by Django 5.0.6 on 2024-05-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_advertisement_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='fuel_type',
            field=models.CharField(max_length=32),
        ),
    ]
