# Generated by Django 5.0.6 on 2024-05-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisement_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='color',
            field=models.CharField(default='color', max_length=16),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='engine',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='mileage',
            field=models.FloatField(null=True),
        ),
    ]
