# Generated by Django 5.0.6 on 2024-07-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_alter_carimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvertisement',
            name='watch_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
