# Generated by Django 5.0.6 on 2024-05-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_advertisement_color_advertisement_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='color',
            field=models.CharField(max_length=16),
        ),
    ]
