# Generated by Django 5.0.6 on 2024-05-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_alter_advertisement_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
