# Generated by Django 5.0.6 on 2024-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_advertisement_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
