# Generated by Django 5.0.6 on 2024-06-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_carimage_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvertisement',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='media/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
