# Generated by Django 5.0.6 on 2024-06-14 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_caradvertisement_image_delete_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.caradvertisement')),
            ],
        ),
    ]
