# Generated by Django 5.0.6 on 2024-06-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caradvertisement',
            name='image',
        ),
    ]
