# Generated by Django 5.0.6 on 2024-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_alter_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='your_email',
            field=models.CharField(default='gmail@gmail.com', max_length=32),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='your_name',
            field=models.CharField(default='name', max_length=32),
        ),
    ]
