# Generated by Django 5.0.6 on 2024-07-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_alter_carimage_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='caradvertisement',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.city'),
        ),
    ]
