# Generated by Django 5.0.6 on 2024-05-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_alter_advertisement_your_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='media/%Y/%m/%d'),
        ),
    ]
