# Generated by Django 5.0.6 on 2024-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_alter_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='hatch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='parking_radar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rear_view',
            field=models.BooleanField(default=True),
        ),
    ]
