# Generated by Django 5.0.6 on 2024-05-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_advertisement_abs_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='hatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rear_view',
            field=models.BooleanField(default=False),
        ),
    ]
